name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate debug keystore
      run: |
        keytool -genkey -v -keystore app/debug.keystore -storepass ${{ secrets.KEYSTORE_PASSWORD }} -alias androiddebugkey -keypass ${{ secrets.KEYSTORE_PASSWORD }} -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -ext "SAN=dns:localhost,ip:127.0.0.1"
    - name: Generate signed debug APK
      run: |
        ./gradlew :app:assembleDebug
      env:
        ORG_GRADLE_PROJECT_DEBUG_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        ORG_GRADLE_PROJECT_DEBUG_KEY_ALIAS: androiddebugkey
        ORG_GRADLE_PROJECT_DEBUG_KEY_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
    - name: Upload debug APK
      uses: actions/upload-artifact@v2
      with:
        name: debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
